import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { ThemeProvider } from "@/theme";
import { DashboardLayout } from "@/layouts/dashboard";


const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap", // best practice untuk menghindari FOIT
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <ThemeProvider>
          <DashboardLayout>
            {children}
          </DashboardLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
